### ISSUE TITLE
Layout is not responsive

### ISSUE THREAD

**Issue by mathiash98** [fribyte-code/boskonf.no#10]
![IMG_6069](https://github.com/fribyte-code/konferanse/assets/5204006/eaa388b0-cac8-4b9b-9235-ac1d0b8cb4ca)

**Comment by SindreKjelsrud** [comment]
Program is not responsive on mobile. Model: iPhone 13

![image](https://github.com/fribyte-code/boskonf.no/assets/93219711/627ca9d4-9524-485d-b1b7-4f0035d1cb89)

**Comment by timharek** [comment]
This is because the labels there are using `position: absolute`. I can check it out later.

**Comment by mathiash98** [comment]
> This is because the labels there are using `position: absolute`. I can check it out later.

`position: absolute` 😨

**Comment by timharek** [comment]
Added a new fix in #17
