### ISSUE TITLE
Videos not rendering in browser

### ISSUE THREAD

**Issue by Cengelsen** [fribyte-code/boskonf.no#21]
It looks like the videos are not being imported or rendered in the browser properly. The picture below is taken in Firefox 119.0.1 and Chromium 119.0.6045.123 on Fedora 39 with Gnome 45.1.

![boskonf-problem](https://github.com/fribyte-code/boskonf.no/assets/78857869/0d4d3c93-5969-4bfb-b5b4-db2bb8a2ff17)

**Comment by mathiash98** [comment]
Hmm still works on iPhone... Does the chromium tab work?

Maybe we need to send mine type in the http response from storage server

**Comment by polsevev** [comment]
Still works on firefox for me

**Comment by polsevev** [comment]
Perhaps a caching issue? Try clearing browser cache?

**Comment by polsevev** [comment]
@Cengelsen Klarer du gjenprodusere det på flere maskiner?

**Comment by Cengelsen** [comment]
Nei, klarer ikke reprodusere. Det  virker som at det er et problem på spesifikt den stasjonære maskinen. Jeg har ingen problemer på mobil, eller på bærbar maskin med fedora 39. 

Det tilsynelatende ikke et problem med innlastingen av videoen, men kompatibilitet. 
![Skjermbilde fra 2023-11-17 00-45-47](https://github.com/fribyte-code/boskonf.no/assets/78857869/1000590f-055e-4a74-94aa-bbc131e69e05)

**Comment by Celsiusss** [comment]
Kom på at Fedora fjernet video og lyd codecs for en stund siden pga potensielle legal issues. Du må nok installere disse manuelt.

https://docs.fedoraproject.org/en-US/quick-docs/installing-plugins-for-playing-movies-and-music/

**Comment by Cengelsen** [comment]
bruh... Nice! det fikset det!
