### ISSUE TITLE
:money_with_wings: Add more info in "Bli-Sponsor"-section

### ISSUE THREAD

**Issue by SindreKjelsrud** [fribyte-code/boskonf.no#27]
Some info about how sponsors are recognized and acknowledged at the conference with some benefits.

Benefits can be like:
- Our gratitude and thanks (social-media posts)
- Logo on website
- Roll-up banner on conference (if they have one themselves)
- Use BOSkonf logo themselves

We should discuss a sponsor-price on a meeting internally, and if this should be added to the section :sweat_smile:

**Comment by nheek** [comment]
Okay, this must be me but I don't see the "Bli sponsor" section 😭😭

**Comment by SindreKjelsrud** [comment]
> Okay, this must be me but I don't see the "Bli sponsor" section 😭😭

@nheek https://boskonf.no/bli-sponsor

**Comment by nheek** [comment]
Oh we don't have it linked yet? Should we add it on the navbar?

**Comment by SindreKjelsrud** [comment]
Good catch, that would be nice! :100:

**Comment by polsevev** [comment]
Any progress on this? @nheek
