### ISSUE TITLE
 [ :recycle: REDESIGN ] :construction_worker: Set up a dev-subdomain

### ISSUE THREAD

**Issue by SindreKjelsrud** [fribyte-code/boskonf.no#32]
> *REDESIGN-tagged issues refers to branch [`/redesign`](https://github.com/fribyte-code/boskonf.no/tree/redesign)*

Would be a nice feature to see stuff in development for the website without having to run website locally :blush:

**Comment by mathiash98** [comment]
fixed in #34 hosted on https://ny.boskonf.fribyte.no
